//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "MiniRover_Native.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_MiniRover_Native_MiniRover_Native_Board::WifiRssi___STATIC__I4,
    Library_MiniRover_Native_MiniRover_Native_Board::SetWifiPowerSave___STATIC__BOOLEAN__BOOLEAN,
    Library_MiniRover_Native_MiniRover_Native_Board::FreeMemory___STATIC__I4__I4,
    Library_MiniRover_Native_MiniRover_Native_Camera::Init___STATIC__I4__I4__I4,
    Library_MiniRover_Native_MiniRover_Native_Camera::Stream___STATIC__VOID__I4__I4__I4,
    Library_MiniRover_Native_MiniRover_Native_Camera::Configure___STATIC__BOOLEAN__I4__I4,
    Library_MiniRover_Native_MiniRover_Native_Camera::SetOrientation___STATIC__VOID__BOOLEAN__BOOLEAN,
    Library_MiniRover_Native_MiniRover_Native_Camera::GetStat___STATIC__I4__I4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_MiniRover_Native =
{
    "MiniRover.Native",
    0xE9C1DBF0,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
