//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "MiniRover_Native.h"
#include "MiniRover_Native_MiniRover_Native_Board.h"

using namespace MiniRover_Native::MiniRover_Native;


HRESULT Library_MiniRover_Native_MiniRover_Native_Board::WifiRssi___STATIC__I4( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        signed int retValue = Board::WifiRssi(  hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_INT32( stack, retValue );
    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_MiniRover_Native_MiniRover_Native_Board::SetWifiPowerSave___STATIC__BOOLEAN__BOOLEAN( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        bool param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_bool( stack, 0, param0 ) );

        bool retValue = Board::SetWifiPowerSave( param0, hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_bool( stack, retValue );
    }
    NANOCLR_NOCLEANUP();
}
