//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "MiniRover_Native.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_MiniRover_Native_MiniRover_Native_Board::WifiRssi___STATIC__I4,
    Library_MiniRover_Native_MiniRover_Native_Board::SetWifiPowerSave___STATIC__BOOLEAN__BOOLEAN,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_MiniRover_Native =
{
    "MiniRover.Native",
    0x675E94B9,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
