//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "MiniRover_Native.h"
#include "MiniRover_Native_MiniRover_Native_Camera.h"

using namespace MiniRover_Native::MiniRover_Native;


HRESULT Library_MiniRover_Native_MiniRover_Native_Camera::Init___STATIC__I4__I4__I4( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 0, param0 ) );

        signed int param1;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 1, param1 ) );

        signed int retValue = Camera::Init( param0, param1, hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_INT32( stack, retValue );
    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_MiniRover_Native_MiniRover_Native_Camera::Stream___STATIC__VOID__I4__I4__I4( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 0, param0 ) );

        signed int param1;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 1, param1 ) );

        signed int param2;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 2, param2 ) );

        Camera::Stream( param0, param1, param2, hr );
        NANOCLR_CHECK_HRESULT( hr );

    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_MiniRover_Native_MiniRover_Native_Camera::Configure___STATIC__BOOLEAN__I4__I4( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 0, param0 ) );

        signed int param1;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 1, param1 ) );

        bool retValue = Camera::Configure( param0, param1, hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_bool( stack, retValue );
    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_MiniRover_Native_MiniRover_Native_Camera::SetOrientation___STATIC__VOID__BOOLEAN__BOOLEAN( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        bool param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_bool( stack, 0, param0 ) );

        bool param1;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_bool( stack, 1, param1 ) );

        Camera::SetOrientation( param0, param1, hr );
        NANOCLR_CHECK_HRESULT( hr );

    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_MiniRover_Native_MiniRover_Native_Camera::GetStat___STATIC__I4__I4( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 0, param0 ) );

        signed int retValue = Camera::GetStat( param0, hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_INT32( stack, retValue );
    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_MiniRover_Native_MiniRover_Native_Camera::SetControl___STATIC__I4__I4__I4( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 0, param0 ) );

        signed int param1;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 1, param1 ) );

        signed int retValue = Camera::SetControl( param0, param1, hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_INT32( stack, retValue );
    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_MiniRover_Native_MiniRover_Native_Camera::GetControl___STATIC__I4__I4( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 0, param0 ) );

        signed int retValue = Camera::GetControl( param0, hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_INT32( stack, retValue );
    }
    NANOCLR_NOCLEANUP();
}
