//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef MINIROVER_NATIVE_H
#define MINIROVER_NATIVE_H

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
#include <nanoPackStruct.h>

struct Library_MiniRover_Native_MiniRover_Native_Board
{
    NANOCLR_NATIVE_DECLARE(WifiRssi___STATIC__I4);
    NANOCLR_NATIVE_DECLARE(SetWifiPowerSave___STATIC__BOOLEAN__BOOLEAN);

    //--//
};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_MiniRover_Native;

#endif // MINIROVER_NATIVE_H
